name: Update File Tree
on: push
jobs:
  generate-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get install tree
          tree -L 3 --dirsfirst -I "node_modules|dist" >> README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update file tree in README"
