name: Update Directory Tree
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [main, master]
    paths-ignore: ['README.md']

permissions:
  contents: write
  pull-requests: write

jobs:
  update-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (authenticated)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Git environment
        run: |
          git config --global user.name "Ahmad4321"
          git config --global user.email "ahmadjaved870@gmail.com"
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GH_PAT }} | base64)"

      - name: Install tree command
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate directory structure
        run: |
          # Generate tree between markers
          tree -L 3 --dirsfirst -I "node_modules|.git|dist|.github" > tree.txt
          awk -v tree="$(cat tree.txt)" '
          /<!-- TREE START -->/ {print; print "```"; print tree; print "```"; skip=1}
          /<!-- TREE END -->/ {skip=0}
          !skip {print}
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update directory tree structure"
          token: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref_name }}
