name: Curation System
on:
  push:
    branches: [ main, master ]
    paths:
      - '!README.md'

jobs:
  generate-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.Rice-Trait-curation }}
          persist-credentials: true

      - name: Setup Git
        run: |
          git config --global user.name "Ahmad4321"
          git config --global user.email "ahmadjaved870@gmail.com"

      - name: Generate tree
        run: |
          sudo apt-get install -y tree
          # Clear previous tree section
          sed -i '/## Project Structure/,/```/{//!d}' README.md
          # Add new tree
          echo -e "\n## Project Structure\n\`\`\`" >> README.md
          tree -L 3 --dirsfirst -I "node_modules|.git|dist" >> README.md
          echo "\`\`\`" >> README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update project tree"
          token: ${{ secrets.Rice-Trait-curation }}
